# Generated by Django 4.1.7 on 2023-03-01 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tasks", models.CharField(help_text="Задание:", max_length=250)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="Статус выполнения:"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 3, 1, 2, 24, 17, 167981),
                        help_text="Задание создано:",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 3, 8, 2, 24, 17, 167981),
                        help_text="Срок по заданию до (по умолчанию 7 дней):",
                    ),
                ),
                (
                    "completed",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Задание переведено в статус 'Выполнено':",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
