# Generated by Django 4.1.7 on 2023-03-01 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 1, 2, 29, 0, 454592),
                help_text="Задание создано:",
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 8, 2, 29, 0, 455592),
                help_text="Срок по заданию до (по умолчанию 7 дней):",
            ),
        ),
    ]
